### ISSUE TITLE
Ankimote support

### ISSUE THREAD

**Issue by dochypermoose** [nogira/anki-minimal-theme#11]
Hey there. Love your add-on, it's really great (just what I needed). How would I get his working with Ankimote (either to reposition where Ankimote shows up) or to give Ankimote a similar icon (like a remote or QR code type icon)?

![image](https://user-images.githubusercontent.com/25800800/143975428-7101c9c1-4eef-4cd4-8e97-8218bf344f7b.png)

**Comment by nogira** [comment]
done :)
