### ISSUE TITLE
Icons Not Centered 

### ISSUE THREAD

**Issue by nmeed** [nogira/anki-minimal-theme#15]
The icons in the middle (deck/browse/sync/...) are not centered. From the left edge of my screen to the edge of the decks icon it's ~491 pixels whereas from the right edge to the edge of the sync button it's ~531 pixels. I would really appreciate it if you could fix that.

**Comment by nogira** [comment]
are you using anki version 2.1.50?

**Comment by nmeed** [comment]
Yes I am. 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/37801365/164710721-5b597f04-baa3-4c0f-888a-af8378a0bac9.png">

**Comment by nogira** [comment]
ah, my addon was conflicting with amboss addon

fixed now
