### ISSUE TITLE
Icon for Sync button missing

### ISSUE THREAD

**Issue by DarcCrusader** [nogira/anki-minimal-theme#16]
**Describe the bug**
The symbolic icon for the sync button in the top actions row is missing.

**To Reproduce**
1. Install Anki
2. Install anki-minimal-theme Addon
3. Restart Anki to apply changes
4. The minimal theme replaces the text based action buttons in the top bar with icons, exept the sync button which stays as text.

**Expected behavior**
All text based action buttons in the top row get replaced by symbol based buttons.

**Screenshots**

![Screenshot from 2023-04-26 22-35-04](https://user-images.githubusercontent.com/121302463/234696157-4c586120-ccf8-49ed-a1ca-92ce7b332135.png)

**Software Used (please complete the following information):**
 - OS: Debian / Linux
 - Anki Version: 2.1.61

**Additional context**
Sadly. the visual inconsistency makes the otherwise very beautiful theme not very usable at the moment.

**Comment by boydkelly** [comment]
Was going to report this as well....

**Comment by nogira** [comment]
fixed
