### ISSUE TITLE
Sync Button

### ISSUE THREAD

**Issue by nmeed** [nogira/anki-minimal-theme#2]
I noticed you stated that the sync button spins, but for me it does not. However I must say that one I don't personally care much about. If you could please however have the color of the sync icon change to match the default Anki "sync" button behavior. Which is to say when it does need to be synced, it turns blue, and as it's syncing it turns orange (if I'm not mistaken). Fantastic add-on and fantastic support.

**Comment by nogira** [comment]
are you using  anki 2.1.45? its out of beta as a 'release candidate', but the main dev isn't releasing to everyone until the end of the month so people have time to update their addons
[download from here (anki-2.1.45+rc1)](https://apps.ankiweb.net/downloads/beta/)

the version for < 2.1.44 doesn't have that feature

also, yes the icon changes color like default anki too

**Comment by nmeed** [comment]
Thank you for the quick reply and for being so proactive with updating the add-on. I'll be sure to update just as soon they release it officially as I really would rather not risk messing with it at the moment.
