### ISSUE TITLE
Updated to 2.1.45 and the addon is giving me an error message.

### ISSUE THREAD

**Issue by woofingcough** [nogira/anki-minimal-theme#4]
The message reads:

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Minimal Theme⁩':
⁨Traceback (most recent call last):
  File "/Users/XXX/Library/Application Support/Anki2/addons21/867316254/files/common_imports.py", line 40, in <module>
    with open(f'{addon_path}/../user_files/config.json', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/XXX/Library/Application Support/Anki2/addons21/867316254/files/../user_files/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt/addons.py", line 217, in loadAddons
  File "/Users/XXX/Library/Application Support/Anki2/addons21/867316254/__init__.py", line 31, in <module>
    from .files import editor_tags
  File "/Users/XXX/Library/Application Support/Anki2/addons21/867316254/files/editor_tags.py", line 27, in <module>
    from .common_imports import *
  File "/Users/XXX/Library/Application Support/Anki2/addons21/867316254/files/common_imports.py", line 43, in <module>
    with open(f'{addon_path}/../user_files/config.json', 'w') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/XXX/Library/Application Support/Anki2/addons21/867316254/files/../user_files/config.json'

Changed my name to XXX for privacy.

What should I do? Should I just disable it for the time being?

**Comment by nogira** [comment]
hmm, thats really weird; the code that crashes is specifically in a statement that is supposed to catch crashes before they crash the program so it doesn't crash 🤔

guess i'll have to find another way to do it


as a quick fix you can copy the user_files folder from the files here in github into your addon folder.
In anki:
`Tools` -> `Add-ons` -> `Minimal Theme` -> `View Files` -> Paste `user_files` folder

**Comment by woofingcough** [comment]
I'll try it! Thanks!

**Comment by nogira** [comment]
fixed :)
