### ISSUE TITLE
Not working in 2.1.46

### ISSUE THREAD

**Issue by xflashkey** [nogira/anki-minimal-theme#6]
![image](https://user-images.githubusercontent.com/72907488/129938067-1f201e33-74ce-41be-b3c1-67be7ee8449d.png)
![image](https://user-images.githubusercontent.com/72907488/129938101-879f101c-27f3-4f22-a5f9-bf877216bf3d.png)

**Comment by nogira** [comment]
I assume the bug is because of the different language. I'll see if I can fix it with RegEx

not sure why the tag icon isn't appearing though, it shows up fine for me when i change the language

**Comment by nogira** [comment]
fixed

**Comment by xflashkey** [comment]
Thank u but the tag icon is not working [image: image.png] :(
