### ISSUE TITLE
Gear and tag icon not applied 

### ISSUE THREAD

**Issue by xflashkey** [nogira/anki-minimal-theme#7]
^ I try uninstalling other complements but nothing
![image](https://user-images.githubusercontent.com/72907488/130330632-84c10d11-b9b0-4be6-80c3-ab6cbf63529e.png)
![image](https://user-images.githubusercontent.com/72907488/130330638-d4c17174-dcea-40d5-bf0f-8dd81eaf5b3c.png)
![image](https://user-images.githubusercontent.com/72907488/130330646-d7950370-a686-4847-8922-03ac5f176d16.png)

**Comment by nogira** [comment]
it works fine on mine, even when I change the language; not sure what the problem is

**Comment by xflashkey** [comment]
Are u trying on windows?

**Comment by nogira** [comment]
no, i dont have windows

i just updated the addon to change how the file path is retrieved. does that fix it?

**Comment by xflashkey** [comment]
idk, what do u think? [image: image.png][image: image.png]
