### ISSUE TITLE
Image full screen bug [Windows]

### ISSUE THREAD

**Issue by betty2310** [nogira/anki-minimal-theme#8]
I'm using Anki ver 2.1.46 and after update, I had this error.

![image](https://user-images.githubusercontent.com/75170473/130726033-40aa5ad6-888a-47da-a8af-4a48575cac11.png)

Try to uninstall and download again but it still happens

**Comment by nogira** [comment]
I can't replicate the bug so i reverted the addon back to the previous version. does that fix it?

**Comment by adamhl8** [comment]
I'm having the same issue on Anki version 2.1.47.

**Comment by nogira** [comment]
oh. can you check the addon doesn't have an update pls?
Tools → Add-ons → Check for Updates

**Comment by shardul-shah** [comment]
@nogira Yes, it will be a similar solution but I recommend using em for responsiveness. 

I agree, the !important rule not working is weird, especially as it's only on Windows and not on Mac.
I suspect OS-specific reasons.

The fix will surely work. Good luck!

If you are worried about affecting Macs when not needed, you can use `os` module and make a conditional depending on if it's Mac or Windows OS.
