### ISSUE TITLE
Sync button does not show up

### ISSUE THREAD

**Issue by imaori** [nogira/anki-minimal-theme#9]
The Sync bottom does not show up, I can press on sync "blindly though".
- Windows 11, 64bit.
- Version ⁨2.1.46 (94913ec2)⁩
![image](https://user-images.githubusercontent.com/51215122/142038040-2fca1562-d83f-4624-8c1d-e1e52859ef74.png)

@nogira

**Comment by nogira** [comment]
fixed :)
